main: net.simplyvanilla.simplyrank.SimplyRankPlugin
name: SimplyRank
version: @version@
api-version: 1.19

author: Simply Vanilla
website: https://github.com/SimplyVanilla/SimplyRank

depend: [PlaceholderAPI, MiniPlaceholders]

commands:
  simplyrank:
    description: Rank management command
    usage: |
      /simplyrank create RANK COLOR [PREFIX] - Creates a new rank.
      /simplyrank set PLAYER RANK - Sets the primary rank of a player.
      /simplyrank add PLAYER RANK - Add rank to a player.
      /simplyrank get PLAYER - Get all ranks of a player.
      /simplyrank rem PLAYER RANK - Remove rank from a player.
    permission: simplyrank.manage

permissions:
  simplyrank.manage:
    description: whether the player can change other player's rank
    default: op

  simplyrank.joinfullserver:
    description: whether the player can join a full server
    default: false
