main: net.simplyvanilla.simplyrank.SimplyRankPlugin
name: SimplyRank
version: @version@
api-version: 1.18

depend:
  - PlaceholderAPI

commands:
  simplyrank:
    description: Rank management command
